### ISSUE TITLE
Container not even starting in QNAP ContainerStation

### ISSUE THREAD

**Issue by raylanelliot** [jlesage/docker-crashplan-pro#107]
I'd say I have decent experience with docker-crashplan-pro as I've successfully configured it on a handful of QNAPs. But my only experience with it is on a QNAP.

To that end, I have acquired a new QNAP for a client, trying to configure this, and the Container won't even start. I click the Start option, it seems to start for a split second, and immediately quits.

Console repeatedly lists:

standard_init_linux.go:187: exec user process caused "exec format error" 

...every time I attempt to start. Any ideas? Much appreciated for any and all help!

**Comment by bigtfromaz** [comment]
It's possible that the CrashPlan Pro image is a victim rather than a cause.  

Have you tried other images to determine if Docker is working correctly?

If so, then perhaps there's an environmental issue with the QNAP and Docker configurations.  

Check out this link from StackOverflow.  It looks like this person had a similar error and resetting Docker fixed the issue:  [https://stackoverflow.com/questions/48236057/how-can-i-fix-standard-init-linux-go187-exec-user-process-caused-exec-format](https://stackoverflow.com/questions/48236057/how-can-i-fix-standard-init-linux-go187-exec-user-process-caused-exec-format)

**Comment by raylanelliot** [comment]
I have verified other containers are working properly on this QNAP.

**Comment by raylanelliot** [comment]
Boom! That is the issue. It is an ARM based QNAP. Thank you for the guidance; definitely will not purchase another ARM based QNAP now that I know this!

Thank you for your guidance.
