### ISSUE TITLE
Storage folder not visible in CrashPlan application

### ISSUE THREAD

**Issue by georgopo** [jlesage/docker-crashplan-pro#119]
I am having a similar issue like this one: https://github.com/jlesage/docker-crashplan-pro/issues/1

I am not able to view storage folder at all, after installing CPP. Only Config folder is visible, but nothing else.
I am using telnet and command line as local admin for the installation, as per your instructions, container is created as it should, but when I run the app, the folder is not visible.

System: QNAP TS-453A
Firmware: 4.3.3
Command line: 
docker run -d \
    --name=crashplan-pro \
	-e USER_ID=0 -e GROUP_ID=0 -e TZ=Etc/UTC -e KEEP_APP_RUNNING=1 \
    -p 5800:5800 \
    -v /docker/appdata/crashplan-pro:/config:rw \
    -v /share/CACHEDEV1_DATA:/storage:ro \
    jlesage/crashplan-pro

/share/CACHEDEV1_DATA is a real folder with all the NAS shared folders in it.

Please advise.

**Comment by jlesage** [comment]
Within the CrashPlan UI, do you see the `/storage` folder ?  Note that you probably have to scroll down to see it.

**Comment by georgopo** [comment]
No, I can see the Device id (7cd43ae6) then, Root, and under that config. No storage directory.
I have tried multiple re-installations, remove docker and ContainerStation, clean up. Nothing worked.

storage is visible in Container settings as shared folder, like config.

**Comment by jlesage** [comment]
Can you provide a screenshot of what you are seeing, just to make sure we are on the same page?

**Comment by georgopo** [comment]
![settings](https://user-images.githubusercontent.com/16000228/44027801-af107fc0-9eef-11e8-9a0c-be4befd88ffc.JPG)
![contents](https://user-images.githubusercontent.com/16000228/44027802-af27b852-9eef-11e8-86ea-a18f4400334d.JPG)
![config](https://user-images.githubusercontent.com/16000228/44027803-af410faa-9eef-11e8-8ed7-c453f288dc12.JPG)
![root](https://user-images.githubusercontent.com/16000228/44027804-af566ca6-9eef-11e8-8cfc-73b2f7135c2c.JPG)

**Comment by jlesage** [comment]
You seem to be in the  "Get files" screen.

If you want to select to files to backup, click on `Home`, then `Details` and finally `Manage Files`.  From there, you should see (by scrolling down) the `/storage` folder under `Root`.

**Comment by georgopo** [comment]
Ok, that worked. However now I am back to Issue #1...
![storage](https://user-images.githubusercontent.com/16000228/44028475-eb51c71c-9ef1-11e8-8449-e9c642335936.JPG)

**Comment by jlesage** [comment]
Do you see your files if you run the following command:
```
docker exec crashplan-pro ls -l /storage
```

**Comment by georgopo** [comment]
![docker](https://user-images.githubusercontent.com/16000228/44033692-16b4538c-9f03-11e8-94cf-f6fadbe5a920.JPG)

**Comment by jlesage** [comment]
Cool, glad to know that it's now working :)

**Comment by georgopo** [comment]
Without changing anything, I just left it running to start backing up during the night, I checked this morning and had backed up 0 files. I opened the "Manage files", folders are checked, however I you open them, there is nothing inside.

I also ran "docker exec crashplan-pro ls -l /storage" again and returns "total 0"...

**Comment by georgopo** [comment]
![missing](https://user-images.githubusercontent.com/16000228/44079379-c418e32e-9fa0-11e8-8037-a5db3140bd3d.jpg)

**Comment by jlesage** [comment]
You seems to have an issue with the shared folders.  The data should not disappear like this.  Also, if you restart the container and end up with the wizard, it's because the mapping to `/config` is not wokring properly.  Is your QNAP firmware and Docker application up-to-date?

Also, according to other users, it seems that shared folder should be defined like this instead:
```
    -v /share/Container/appdata/crashplan-pro:/config:rw
    -v /share:/storage:ro
```

Maybe you could try to create the container from the UI instead?

**Comment by jlesage** [comment]
So maybe the way to proceed is to add multiple shared folders?  Is it working better if everything is done from the UI?

**Comment by georgopo** [comment]
Not really... I cannot add more folders later like this. That is why I wanted to add "/share" instead.
Also, when restarting, sometimes I am getting 500 errors. Last one was "not enough space".

**Comment by georgopo** [comment]
What I did in the end...

I created the Container within the UI, by setting up parameters of USER_ID and GROUP_ID to 0, and sharing only one folder (ex MyQnap/Documents). From UI you cannot access folder above "MyQnap" or whatever yo have named it.
Then, I stopped the container and ContainerStation.
Opened File Station and navigated to:
/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/container/{container_hash}/

There I had to edit 3 configuration files:
config.v2.json, hostconfig.json, qnap.json
and replace "/share/Documents" with "/share/CACHEDEV1_DATA" (parent of Documents that contains all QNAP Shared data)
Started ContainerStation and Container and selected all the folders for backup.
Since then it works fine.

note: When I was selecting "MyQnap/Documents" and the other folders, it was backing up few kilobytes. The path in configuration files was /share/Documents and looks like CrashPlan cannot access that, but can access "/share/CACHEDEV1_DATA/Documents"

**Comment by FizzGiGG** [comment]
georgopo, I'm on a QNAP TS-453A and experience the same exact problems. I am able to create a new crashplan-pro container using the command line with similar arguments/options as you. Even a restart of the container will create a new image. I also creates new volumes on /. It's basically unusable. Every reboot creates new volumes and images.

I'm trying to do a full restore of my NAS and this is seriously getting in the way.

**Comment by bigtfromaz** [comment]
@FizzGiGG It would be a good idea to share your run statement.

**Comment by FizzGiGG** [comment]
docker run -d /
--name=crashplan-pro /
-p 5800:5800 /
-e USER_ID=0 /
-e GROUP_ID=0 /
-e TZ=America/Chicago /
-v /share/CACHEDEV1_DATA/Container/persistent-data/crashplan-pro:/config:rw /
-v /share/CACHEDEV1_DATA:/storage:rw /
-v /share/external/DEV3302_2:/external:rw /
jlesage/crashplan-pro

**Comment by bigtfromaz** [comment]
Can you provide some clarity when you say "Even a restart of the container will create a new image."  Do you mean it's always re-syncing content?

From host machine, when the container is stopped, do you see folder with the name:

/share/CACHEDEV1_DATA/Container/persistent-data/crashplan-pro?

And, are there a number of subfolders with these names?:  .code42, .crashplan, .oracle_jre_usage, .pki, bin, cache, conf, log, repository, var and xdg?  

If there are no files then your crashplan metadata "config" is not being persisted on the host.

If so, in the log folder there should be a number of files named *.log.  Check those out for errors.

When the container is running, you should be able to see the exact same content in /config as you do in /share/CACHEDEV1_DATA/Container/persistent-data/crashplan-pro.  

From inside the container, do you see the content that's supposed to be backed up in /storage and /external?

When you say a "full restore", are you talking about downloading your current crashplan content into a new or reset machine?  If so, have you reviewed and performed the adoption process?  If not I would like to know more about your situation.

**Comment by FizzGiGG** [comment]
I'm attempting to perform a full restore to the same hardware. I re-initialized my QNAP TS-453A which resets it to factory defaults and formats the drives. Freshy fresh! I had too many odd issues occurring, so it was time to bite the bullet and start clean. I backup to the Cloud and to an external USB drive.

I performed the first time configuration of QTS, updated the pre-installed apps, configured the NIC teaming (LAG), IP address, DNS, etc. Once the basic setup was complete, I installed Container Station, left it at it's defaults which places the Container directory at /share/CACHEDEV1_DATA/Container. From there I went ahead and ran the docker command from an SSH session using the admin account (GID:0, UID:0) to create the crashplan-pro container from the jlesage image using the following command (as previously mentioned):

> docker run -d /
> --name=crashplan-pro /
> -p 5800:5800 /
> -e USER_ID=0 /
> -e GROUP_ID=0 /
> -e TZ=America/Chicago /
> -v /share/CACHEDEV1_DATA/Container/persistent-data/crashplan-pro:/config:rw /
> -v /share/CACHEDEV1_DATA:/storage:rw /
> -v /share/external/DEV3302_2:/external:rw /
> jlesage/crashplan-pro

Because the NAS was totally devoid of data, there was no existing /config data, so it creates a new machine id. The container started up wonderfully and created the new /config files and directories, so I performed the adoption process outlined on CrashPlan's support site. Maybe it was a bit out of step, but I then proceeded to make sure that the Container had the correct Auto start, CPU, and Memory settings. When I enabled Auto Start, set the CPU to 70%, and lowered the mem to something like 9G (I have 16GB on NAS), I clicked OK to save. It restarted the crashplan-pro container. This is where things start to go wrong.

During the restart of the container you can see via the Container Station GUI it appears to create a temporary Container. What that means, I don't know. Is it saving the current configuration of the crashplan-pro container to a new temporary container and then creating a new image from that? Forgive my lack on knowledge, I'm very green when it comes to Docker, so bear with me.

After the container restarts, if it doesn't give me some weird error message from Container Station, it will be up and running again... but it's not the same. It's now running off of a new image, and it also created a couple of volumes.

Temporary container:
![image](https://user-images.githubusercontent.com/1538645/53288745-df50bd80-3751-11e9-979c-86c56f7034eb.png)
New volumes created:
![image](https://user-images.githubusercontent.com/1538645/53288747-e4157180-3751-11e9-8cbb-ae987485b384.png)
New image:
![image](https://user-images.githubusercontent.com/1538645/53288749-e8da2580-3751-11e9-9a3f-ca58ed34d20b.png)
Container:
![image](https://user-images.githubusercontent.com/1538645/53288828-2e4b2280-3753-11e9-8aa1-7a7b171118bc.png)

Now it's acting as if I never ran through the adoption process. First time CrashPlan Pro client setup starts again. I've created about 10 new machine_id's during this mess. It's obnoxious.

To your question about the /config data: Shutting down the Container I can still see the "/share/CACHEDEV1_DATA/Container/persistent-data/crashplan-pro" directory and it's filled with all of the goodies I would expect to see (bin, cache, .code42, conf, cp_version, .crashplan, log, machine-id, .pki, repository, var, xdg)... But now because I shutdown the container, it has created another set of volumes, a new image, and voila! I get the first time Crash Plan Pro setup again, and a new machine_id.

It will keep piling on the volumes, images, and new machine_id's.

Yes, I can see the necessary persistent data from within the container.

I hope that paints a better picture for you!

**Comment by bigtfromaz** [comment]
It helps immensely.  First I want to confirm my understanding regarding your process.  Is it correct to say that you created the container from the command line and then made changes to it using the QNAP gui?

**Comment by FizzGiGG** [comment]
@bigtfromaz Yes, that is correct. created the container from the commend line, and then altered the Auto Start, Mem, CPU form the Container Station GUI.

I'll be honest right away here. I'm working on installing Docker and CrashPlan on a completely separate machine now, and will create mount points to my NAS. That way I will only be using the NAS as a NAS. Container Station is too much of an abomination to run anything.

I know this is a CrashPlan question, but do you know if I will have any issues restoring my data from the external USB drive to a completely new machine? I vaguely remember in the adoption process doc it stated something about not liking this, but that would be strange if you couldn't adopt/restore to a completely new machine.

Thanks for taking the time on this. I've been working on this for about 4 days and the wife would like to have her data back, so I made the decision to follow a more standard approach to how everything is run. No more crap QTS apps for me. Vanilla Linux, Windows, Docker from this point forth... nice and clean and supportable.

**Comment by bigtfromaz** [comment]
It appears you do indeed have two images and the crashplan the machine id is probably changing.  It is probably due to QNAP mishandling the situation.  You should consider doing this again but, if you use the command line, always use the command line.  Here is a link to a docker doc for limiting resource use with docker run parameters [https://docs.docker.com/config/containers/resource_constraints/](https://docs.docker.com/config/containers/resource_constraints/)

You can set these on docker run, when creating the container, or using docker update while the container is running.  This should ensure that you only have one image, one container and you can throttle with docker update.

**Comment by bigtfromaz** [comment]
@FizzGiGG and one other note, if you use the command line only, you will be less likely encounter resistance when using CrashPlan support.

**Comment by FizzGiGG** [comment]
Excellent to hear @bigtfromaz . Maybe I'll try that first before tackling the new machine... time to go swap USB drive back to the NAS.

Thanks much!

**Comment by bigtfromaz** [comment]
@FizzGiGG I would.  There are quite a few QNAP users that run this.  My company uses Synology and have used both GUI and command line configuration.  I can't vouch for QNAP but I am pretty sure command line  Linux is command line Linux.

**Comment by FizzGiGG** [comment]
@bigtfromaz Oh it's definitely pretty standard linux, maybe Debian based? It's definitely a bit weird. I believe that Docker cli stuff is all pretty normal though.

Thanks for the pointers, I'll let you know how it goes.

**Comment by FizzGiGG** [comment]
I've built the container using the following command. I believe that this should cover every setting I need, all from the command line. I've added the items in bold...

> docker run -d /
> --name=crashplan-pro /
> **-m 10g** /
> **--cpus=".7"** /
> **--restart unless-stopped /**
> -p 5800:5800 /
> -e USER_ID=0 /
> -e GROUP_ID=0 /
> -e TZ=America/Chicago /
> **-e KEEP_APP_RUNNING=1 /**
> -v /share/CACHEDEV1_DATA/Container/persistent-data/crashplan-pro:/config:rw /
> -v /share/CACHEDEV1_DATA:/storage:rw /
> -v /share/external/DEV3302_2:/external/5TB:rw /
> **-v /share/external/DEV3303_2:/external/8TB:rw /** _Additional USB drive, will be new local backup dest._
> jlesage/crashplan-pro

So after creating it, just looking, not touching; the Container Station GUI doesn't appear that it recognizes the memory, CPU, or start options I provided in the CLI.

![image](https://user-images.githubusercontent.com/1538645/53289943-f6e47200-3762-11e9-81c1-feda399ad291.png)

Running _docker container inspect crashplan-pro_ does indeed show that the options are set for the container.
![image](https://user-images.githubusercontent.com/1538645/53290009-09ab7680-3764-11e9-888b-fd8ba80210fe.png)

So I will see what a restart of the NAS does to Container Station and the crashplan-pro container.

Fingers crossed!

**Comment by FizzGiGG** [comment]
Reboot was successful! It started up, no weird behavior (new volumes, image, etc.)

**Comment by bigtfromaz** [comment]
Excellent.

**Comment by FizzGiGG** [comment]
@bigtfromaz Just a little update here, after all of these days... the restore finished but no files were restored. Only folders. I'm working with CrashPlan support now.

So very frustrating.

Thanks again for the help.

**Comment by bigtfromaz** [comment]
I don't believe Crashplan syncs automatically.  I think you have go the the
UI and restore.
