### ISSUE TITLE
Mapping _all_ host user ids into the container?

### ISSUE THREAD

**Issue by itsthejb** [jlesage/docker-crashplan-pro#125]
Hi there,

This image looks great, and I'm using many of your others as well. So thanks a lot!

The only problem I have getting started with this is the issue of mapping my various host user ids into the container so that all volume files can be seen. I had a search around for the "correct" way to do this, but haven't really succeeded yet. I assume it must be possible, and not _too_ complicated since I only need read-only access to my host files.

Can anyone help and point me in the right direction?

Thanks again!

**Comment by jlesage** [comment]
How are setup the ownership/permissions of your files?  Are your files owned by a common group?

**Comment by itsthejb** [comment]
Hi,

Thanks for getting back to me. Unfortunately not. Some data I want to backup shares a common group, but plenty others don't, since I have a lot of services also running on my system.

I can understand if this isn't an easily served use case. The solution I saw that seemed to make sense was to map /etc/passwd directly into the container. Do you think this makes sense? Other than the plethora of users, my system is otherwise quite straightforward and only for my private use

Thanks again

**Comment by jlesage** [comment]
The "easy" way is to run Crashplan under the root user by setting `USER_ID` and `GROUP_ID` to `0`.  But running as root is usually not the recommended and preferred way.

Also, mapping /etc/passwd is not a solution, since you still need to choose a user under which CrashPlan is running and this user needs to have access to all your files.

The other solution I see is to use the `SUP_GROUP_IDS` variable: if you add all the required groups to this variable, CrashPlan can then access all your files.

**Comment by itsthejb** [comment]
Thanks for your response! I'll give that a try

**Comment by itsthejb** [comment]
Tried with `SUP_GROUP_IDS` - seems to be doing what I need. Thanks!
