### ISSUE TITLE
version confusion 20sep18

### ISSUE THREAD

**Issue by DavidLaidlaw** [jlesage/docker-crashplan-pro#133]
I have several points of confusion, as a Synology DSM user.

The latest version of crashplan pro seems to be 6.8.3

The latest version on this repo seems to be 2.4.1.  Those two versions seem to be in different sequences...

I don't understand the relationship, and my container is complaining (even after updating) that it tried o update but was unsuccessful.   Help!

Thanks!

**Comment by GitAuggie721** [comment]
version 2.4.1 is the container from jlesage and it has crashplan 6.8.2 in it.

The reason your container is complaining is because crashplan 6.8.2 is trying to upgrade itself to 6.8.3 and this is turned off.

In another post jlesage said they would update the container to include the new crashplan version, so stay tuned!

**Comment by jlesage** [comment]
Exactly.  You can now update to the latest image (`v2.5.0`) which include CrashPlan version `6.8.3`.
