### ISSUE TITLE
real-time inotify watching silently not working

### ISSUE THREAD

**Issue by waynedpj** [jlesage/docker-crashplan-pro#148]
ahoy,

  though i am getting no inotify errors as described [in this project's Readme](https://github.com/jlesage/docker-crashplan-pro#inotifys-watch-limit) and [in Code42's support](https://support.code42.com/CrashPlan/6/Troubleshooting/Linux_real-time_file_watching_errors), real-time file watching is not working. `cat /proc/sys/fs/inotify/max_user_watches` is `2097152`.  i have also checked the UID and GID of the container's app, which seem to be fine since the app is able to discover and backup files when manually scanning.

  given my almost nil Docker experience, i have a feeling that it has something to do with this.  however apparently inotify with GNU+Linux should [just work](https://forums.docker.com/t/file-system-events-not-correctly-propagating-from-host-to-container/15201/12)?  but using inotifywatch inside the container and modifying the same file on the host shows no notifications as expected with this issue.

thanks.

**Comment by jlesage** [comment]
What is the underlying file systems on the host?
There are some file systems that may not work with inotify.  NFS or network shares are some examples.

**Comment by waynedpj** [comment]
apologies for the delayed reply: i was hoping that updates to Crashplan and/or your container might fix this issue .. which unfortunately was not the case.

> What is the underlying file systems on the host?

the underlying filesystem is btrfs which i verified is working correctly with inotify outside the container.  in addition, watching a file from inside the container via `inotifyd - test` and changing it outside the container also shows that the changes are indeed being seen within the container.

any other ideas to check?  thanks again for your help.

**Comment by jlesage** [comment]
You can look at `log/service.log.0`, in the directory you mapped to `/config`.  You may have more details about the notify errors.

**Comment by spikedog58** [comment]
I can see this thread hasn't been updated for some time but I seem to have the same problem. Backups work after a scan but changes and new files are not being backed up. If I go into manage files on the UI I can see the new files listed and are selected for backup but they are not being backed up. Backups are set to always run and every 15 minutes but after 2 days these files have still not been backed up.

I have increased inotify watches to 4194304 just to make sure there is no problem and verified that inotify is running by executing tail -f, both on the base operating system and within the docker container after executing docker exec -ti crashplan sh

The crashplan logs do not show any inotify errors or attempts to backup the new files.

I am running on a synology DS1019+. I currently have docker running as root to avoid any permission issues. Here are my env settings
/ # env
APP_USER=app
HOSTNAME=crashplan
USER_ID=0
XDG_CACHE_HOME=/config/xdg/cache
SHLVL=1
HOME=/root
OLDPWD=/config/log
APP_NAME=CrashPlan for Small Business
DISPLAY_HEIGHT=768
GROUP_ID=0
S6_WAIT_FOR_SERVICE_MAXTIME=10000
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
S6_BEHAVIOUR_IF_STAGE2_FAILS=3
XDG_RUNTIME_DIR=/tmp/run/user/app
DISPLAY=:0
LANG=en_US.UTF-8
XDG_DATA_HOME=/config/xdg/data
XDG_CONFIG_HOME=/config/xdg/config
S6_SERVICE_DEPS=1
PWD=/
DISPLAY_WIDTH=1280
KEEP_APP_RUNNING=1
TZ=Australia/Sydney

This doesn't seem to be a common prooblem so I assume it is something with my configuration but I can't work out what that might be.

**Comment by jlesage** [comment]
Anything special about the filesystem on which your files are stored?

**Comment by spikedog58** [comment]
The file system is BTRFS with raid level SHR2 and a single volume. All settings are straight out of the box.

**Comment by spikedog58** [comment]
I've been working on different configurations and real time backup is working now, although I don't know what I've done that could have made that happen.

In case someone else has the problem and might be able to benefit here is my sequence of events.

I'm on a Synology and the GUI doesn't allow me to map /storage to anything other than nas shares so I first tried creating a separate mapping for each share
/storage/movies => /movies
/storage/music => /music etc. Backups worked (they have always worked) but real time monitoring did not

Next I tred mapping /storage directly to /volume1. I had to do this through ssh because the GUI doesn't allow it. Still no real time monitoring.

Then I tried mapping /storage directly to just one of the shares, still not working.

Through all of this I was also scanning and restarting with each change, and there were several maintenance cycles.

Most recently I tried just giving up on /storage and mapped directly to each share by its own name
/movies mapped to /movies etc. Still no luck.

Today I used the Synology GUI to export the configuration to a json file. Then at the top of the volume bindings I added this
`{
         "host_absolute_path" : "/volume1",
         "mount_point" : "/storage",
         "type" : "ro"
      },`
I deleted the existing container and reloaded from this json file and now real time monitoring is working. I still have the mappings directly to shares and that is where all of the backups are selcted. Nothing is backing up through /storage.

As I said, I have no idea why this is working but it is. Maybe this will help someone else.

**Comment by waynedpj** [comment]
ahoy fella frustrated CP users from the future,

  after trying to get this to work for a while i was force to stop using the docker image and instead run CrashPlan PRO aka CrashPlan for Small Business (CPfSB) natively though still in a similar setup i.e. Btrfs, etc.  and amazingly the real time file watching (RTFW) was still not working.  now after a 2+ months  support thread with Code42, my problem is solved and came down to 2 separate problems:

1. during the switch to the new Electron-based Desktop CrashPlan desktop application ~March 2019, the option to enable/disable RTFW was removed from the GUI.  and "somehow" (according to Code42) for my account this setting was turned off during the transfer.  thus since i had no way to see nor edit it in the new desktop application i had assumed that it was now always on.  eventually Code42 figured this out and enabled it for my account. however this still did not get RTFW working for me ..
2. while changing settings in the [web console](https://www.crashplanpro.com/console/) in the various (sometimes repetitive) attempts and suggestions by Code42 to resolve the issue, i discovered independently that there were included old defunct backup paths under `/run/` that were not being shown in the new Electron-based desktop application.  only when i removed these `/run/` paths from every backup set via the web console did RTWF finally start working .. instantly.  Code42 was not aware of the issue and hopefully a bug was filled.

i will add, for those who are interested, that i have used CP for many years.  and while the rep involved was nice enough, the whole support experience was pretty lousy and hastens my search for a FLOSS/open source backup solution: CPfSB is the last closed source/proprietary app that i use and this experience just reinforces the need for an open source backup solution.

regardless thatnks to @jlesage for this great project and help.

peace
