### ISSUE TITLE
Crashplan does not see subfolders

### ISSUE THREAD

**Issue by acere** [jlesage/docker-crashplan-pro#168]
I am running the Crashplan container on a QNAP NAS. I have no problem loading and starting the container and registering the device with the Crashplan server.

The problems start when I want to add files to the Backup set. I browse to the mounted folder and I can only see the top level subfolders, and they all appear empty.

I checked via CLI that the container can read all the files and folders in the mounted folder without any problem.

Suggestions are welcome!

**Comment by jlesage** [comment]
This is probably a permission issue: the user under which the container is running should have read access to the files you need to backup.

**Comment by gatorheel** [comment]
Could be a path problem too.  Can you share the parameters you're using to
create the container?

**Comment by acere** [comment]
I thought so too, but I don't see any clear pattern. Here's on the NAS:
`[/share/CACHEDEV2_DATA/Photos] # ls -la`
 `total 84`
 `drwxrwxrwx   9 admin administrators  4096 2019-03-29 20:27 ./  `
 `drwxrwxrwx   4 admin administrators  4096 2018-02-17 11:52 ../ `
 `drwxrwxrwx 198 admin administrators 12288 2019-03-25 17:34 Backups/`
` -rwxrwx---   1 admin everyone        6148 2018-07-27 15:00 .DS_Store*`
` drwxrwxrwx  30 admin administrators  4096 2019-01-14 09:57 Main/`
 `drwxrwxrwx  11 admin administrators  4096 2019-03-25 18:43 .streams/`
 `drwxrwx---   3 ale   everyone        4096 2018-08-16 21:20 .TemporaryItems/`
 `drwxrwxrwx   2 ale   everyone        4096 2019-03-29 20:27 test/`
 `drwxrwxrwx  17 admin administrators  4096 2019-01-26 14:25 Underwater/`
 `drwxrwxrwx   8 admin administrators  4096 2018-08-23 10:22 Work/`

Here's from the container
<img width="491" alt="Screen Shot 2019-03-29 at 22 45 38" src="https://user-images.githubusercontent.com/13648166/55240692-683ca680-5274-11e9-8476-122ddeaa5132.png">

Here's Crashplan:
<img width="1079" alt="Screen Shot 2019-03-29 at 22 46 51" src="https://user-images.githubusercontent.com/13648166/55240785-a639ca80-5274-11e9-940c-5b65c308d6eb.png">


> This is probably a permission issue: the user under which the container is running should have read access to the files you need to backup.

**Comment by acere** [comment]
Here's the full command
```
docker run -d \
    --name=crashplan-pro \
    -p 5800:5800 \
    -v "/share/CACHEDEV1_DATA/Containers/crashplan/config":"/config":rw \
    -v "/share/CACHEDEV2_DATA":"/storage":ro \
    -e TZ=Asia/Singapore \
    -e CRASHPLAN_SRV_MAX_MEM=4096M \
    jlesage/crashplan-pro:latest
```


> Could be a path problem too. Can you share the parameters you're using to create the container?
> […](#)

**Comment by Tek4** [comment]
@acere You may need to add the environment variables for user and group ID to your docker run command:

`docker run -d --name=crashplan-pro -e USER_ID=XXXX -e GROUP_ID=XXXXX [...]`

To determine `USER_ID` and `GROUP_ID`, first get root access:
`> sudo -i`

Then:
`> id _username_` where _username_ is the user your container runs under.

For example, if you created a `crashplan` user that derives permissions from a group you named `BackupAgentsGroup`, then you should have something like this:

`> id crashplan`
`uid=1010(crashplan) gid=100(users) groups=100(users),65540(BackupAgentsGroup)`

You want to use the _most specific_ user and group IDs. Thus, for the `crashplan` user in the example above, the `USER_ID` is `1010` and the `GROUP_ID` is `65540`. Even though the `crashplan` user is a member of the more general `users` (100) group, you should be using the more specific `BackupAgentsGroup` (65540) — presuming you created a group for backup agents.

Hence, following the same example, your command line should include:
`docker run -d --name=crashplan-pro -e USER_ID=1010 -e GROUP_ID=65540 [...]`

**Comment by Tek4** [comment]
@acere Additionally, I didn't need any double-quotes in my command line. Try this:
```
    -v /share/CACHEDEV1_DATA/Containers/crashplan/config:/config:rw \
    -v /share/CACHEDEV2_DATA:/storage:ro \
```

**Comment by acere** [comment]
@Tek4 That was it, thanks.

I am ashamed to confess I am running the containers as root, but QNAP isn't very friendly when it comes to regular users... The current working command is:
```
docker run -d \
    --name=crashplan-pro \
    -e USER_ID=0 -e GROUP_ID=0 \
    -p 5800:5800 \
    -v /share/CACHEDEV1_DATA/Containers/crashplan/config:/config:rw \
    -v /share/CACHEDEV2_DATA:/storage:ro \
    -e TZ=Asia/Singapore \
    -e CRASHPLAN_SRV_MAX_MEM=4096M \
    jlesage/crashplan-pro:latest
```

> @acere You may need to add the environment variables for user and group ID to your docker run command:
> 
> `docker run -d --name=crashplan-pro -e USER_ID=XXXX -e GROUP_ID=XXXXX [...]`
> 
> To determine `USER_ID` and `GROUP_ID`, first get root access:
> `> sudo -i`
> 
> Then:
> `> id _username_` where _username_ is the user your container runs under.
> 
> For example, if you created a `crashplan` user that derives permissions from a group you named `BackupAgentsGroup`, then you should have something like this:
> 
> `> id crashplan`
> `uid=1010(crashplan) gid=100(users) groups=100(users),65540(BackupAgentsGroup)`
> 
> You want to use the _most specific_ user and group IDs. Thus, for the `crashplan` user in the example above, the `USER_ID` is `1010` and the `GROUP_ID` is `65540`. Even though the `crashplan` user is a member of the more general `users` (100) group, you should be using the more specific `BackupAgentsGroup` (65540) — presuming you created a group for backup agents.
> 
> Hence, following the same example, your command line should include:
> `docker run -d --name=crashplan-pro -e USER_ID=1010 -e GROUP_ID=65540 [...]`

**Comment by Arnvidr** [comment]
Are the defaults for USER_ID and GROUP_ID not as written in the README.md file? I had to add -e USER_ID=1000 -e GROUP_ID=1000 to make this work for me.

**Comment by jlesage** [comment]
Yes the defaults should be `1000`.  You can try to run `docker inspect <container name>` to see which values are used.

**Comment by Arnvidr** [comment]
I think the problem here was my NFS mounts, if the docker container starts before they are mounted, the folders appear empty. I'm sure there are some volume mount options I could use to propagate that problem, but I'll be concentrating on making the nfs mounts run before the docker init script.

**Comment by Tek4** [comment]
@Arnvidr, I too noticed that CIFS mounts don't appear on my Synology, but I hadn't thought about mounting them first before starting docker.

But what happens when there is an eventual network connectivity error (reboot of the file share or VPN disconnect)? Without restarting docker, will the share persist or disappear?

In other words, are you creating fragility?

For the sake of reliability, I'm leaning towards a disk snapshot and have CrashPlan back up the snapshot instead of the network shares. Of course this means the shares will need to be replicated locally and take up disk space. But I actually want a local backup in addition to the cloud.

**Comment by Arnvidr** [comment]
@Tek4 I wouldn't know what happens, but it might be as easy as the mount persisting, and files start showing again when the network recovers (or other fault is fixed). Depends on the underlying reason for these mounts being empty in the first place.

**Comment by Tek4** [comment]
@Arnvidr I did some experimenting, thanks to you. Of course, I'm running a Synology, not QNAP, but this may be of use to you or others:

## Mount remote folders BEFORE starting CrashPlan
I mounted a remote CIFS share with Docker stopped, then started Docker. I can now see the remote files inside of CrashPlan! This didn't seem to be the case when I mounted the remote share with CrashPlan already running.

## What happens when remote share goes down?
Next, I wanted to see what happens if the remote machine is disconnected (i.e., reboot, VPN interruption, network down, etc.) So, I stopped my router's VPN server to cause an interruption.

When I browsed to the remote folder (both in CrashPlan and in Synology's File Station), I got a very long-running "loading"... then, after about a minute or more, the operation timed out. CrashPlan showed a file placeholder (instead of a folder). Synology's File Station simply reported "Operation failed".

**IMPORTANT OBSERVATION:** This long-running timeout interferes with browsing the contents of the parent folder that contains the remote mount. Because I have other data/folders in the parent folder, I think I will create a `remote` sub-folder for the remote mounts. This will avoid delays in accessing other data in the parent folder.

## What happens when remote share reconnects?
But my real interest is what happens when connectivity is restored? Will the remote mount re-appear? So, I re-started my router's VPN server and waited a minute for the remote server to automatically reconnect. Indeed! The remote mount re-appeared! Both in Synology and CrashPlan!

## What happens when Synology reboots?
Finally, I performed a restart (reboot) of my Synology to see if the whole contraption withstands a reboot. Indeed, everything came back up!

## Conclusions
The above is not well-tried and proven, but if my casual testing proves true, there are a couple conclusions worth noting:

(1) Mount remote folders **prior** to starting Docker. Ensure they are selected to "mount automatically on startup".
(2) Consider mounting remote folders inside a stand-alone parent folder. If the remote connection fails, browsing the parent folder causes a long-running "hang" eventually ending in a time-out. Using a stand-alone parent folder for your remote shares avoids having access to other files/folders hang.

**Comment by Arnvidr** [comment]
@Tek4 Great detective work!

For reference, I'm running docker on my main desktop machine, and mounting some folders through NFS. Funnily enough, there's one QNAP and one Synology NAS included in the whole getup.

Anyway, docker is started at bootup by the OS, and I just modified the init script to depend on the netmount service, and everything seems to work as expected now.

**Comment by Tek4** [comment]
@Arnvidr I'm now waiting to see if CrashPlan picks up the selected files. It's been a couple hours and it has not backed up the remote folder yet, despite that the folder is selected and the backup frequenct is set for Every 15 Minutes. I have a suspicion:

Remote mounted folders probably do not support `INOTIFY`, thus I expect CrashPlan won't see changes in the remote folder without running a file scan.

In attempt to trigger a scan, I unchecked the remote folder, confirmed the deletion, then went back in and checked the remote folder. That has triggered the familiar `Scanning backup selection`. We'll see where this leads shortly...

I strongly recommend you confirm remote shares are being picked up, and I'd say it's a very good idea to keep re-checking from time to time until you have confidence.
