### ISSUE TITLE
CrashPlan app v7.0.0 to be released by June 18

### ISSUE THREAD

**Issue by Tek4** [jlesage/docker-crashplan-pro#180]
FYI only:
https://support.code42.com/Release_Notes/CrashPlan_for_Small_Business_release_notes

**Comment by jlesage** [comment]
Thanks, the app is not available yet for download, but I keep an eye on it.

**Comment by Tek4** [comment]
Now available.

![image](https://user-images.githubusercontent.com/921911/59731148-e5374680-91f9-11e9-98cf-6e7a61a7b9c0.png)

**Comment by cerealsoup** [comment]
Never had an update come out while I was actively working on the container. How's this work - what's the usual container update time after a version update?

**Comment by jlesage** [comment]
It depends on how much changes the new CP version have, but it usually take only a few days.

**Comment by jlesage** [comment]
I'm currently working on this one.

**Comment by cerealsoup** [comment]
Thank you, looking forward to it.

**Comment by toledobastos** [comment]
The upgrade killed dynek's package, so it should be pretty major. I switched to docker hoping it would work, but no luck.

I'm getting "Code42 wasn't able to upgrade but will reattempt in one hour." Under the backup set it reads "Version mismatch - You must upgrade to use this destination."

I looked into CrashPlan dashboard and my device is offline. Until yesterday it would still talk to CP central, but no more.

I'm assuming this is due to the release of ver 7.0.0, as my app is ver 6.9.4.502. I'm curious to know how the update works.

**Comment by DavidLaidlaw** [comment]
The way it works is that jlesage very kindly updates her open-source docker implementation to use the latest version of CP.  As she reported 2 days ago, she is working on it (Thanks jlesage!).  When she's got it working, she'll indicate that via github.  If you're on this issue, you should get notified.  Otherwise, you can check back to see if it's done or have github notify you when changes are made.  At that point, you'll need to download, install, and run the new version of the docker package, which will run the latest CP.

**Comment by toledobastos** [comment]
> you'll need to download, install, and run the new version of the docker package

Thanks for that. Do you know if that requires adopting the current machine (I think they call it "replacing a device" these days)? 

I'm just wondering if it's worth scanning all my files if the current docker installation will have to be adopted and then a new scan required.

**Comment by Tek4** [comment]
toledobastos, no, you just download and replace the Docker container. Your settings aren't b destroyed by this process so it's just a simple upgrade.

**Comment by steveschow** [comment]
My backups have stopped working.  Must be because of the crash plan upgrade on the server end.  Hope the updated docker will come soon.

**Comment by Tek4** [comment]
DavidLaidLaw, If you are presuming "she", I believe you might be incorrect.

steveschow, An ongoing problem with this particular solution is Level 42 "kills" old versions from working the moment they release a new one. It takes Jocelyn a few days to update the container and you go without backups during that time period. Because it's a secondary/tertiary backup in my application this doesn't worry me too much, but it is a hassle when updates are frequent.

**Comment by steveschow** [comment]
Its really dumb of Level42 to do that.  Requiring us to update our clients in order to continue making backups every time they decide on a whim to upgrade their servers is very poor support on their part.

**Comment by Tek4** [comment]
Steve, I think you've got the wrong perspective. Level 42 supports their clients very well. This is an "unauthorized" client that a talented person assembled to make CrashPlan work on unsupported hardware.

**Comment by steveschow** [comment]
you don't have to agree with me, but my perspective is right on point.  This is the second time in a few months they have broken my backups.  Granted I had to wait a little longer because of docker, but even without docker..its still a fact they are breaking people's backup until such people are able to update the software on all of the machines they are backing up..which may or may not always be such a trivial thing.  It happens to be non-trivial for us on docker sure, but that doesn't mean everyone else off of docker will automatically get their client updated.  They are presuming their auto update will handle it...but this is poor choice on their part.  Sorry, but that's my opinion.  If they are going to roll out non backwards compatible server changes, they need a better then that.

**Comment by Tek4** [comment]
Yeah, we disagree. They aren't breaking anything. Their clients update automatically. Who are you to demand that support a setup you created that they never supported in the first place?

In fact, it might be their business plan to make things difficult for unsupported hardware ON PURPOSE because they want you to buy multiple desktop client licenses. Instead, you have a setup that potentially backs up numerous desktops and uses far more of their storage. So you're basically screwing them and then complaining about it.

Unsupported is unsupported. This is a poor man's setup and it comes with issues.

**Comment by steveschow** [comment]
lighten up dude.  I didn't demand anything.  I criticized.  And again I say, its very poor design decision on Level42's part to roll out a server change that breaks clients...REGARDLESS of the fact that they THINK everyone's clients will automatically update.  I don't really want to argue with you, we can just agree to disagree.  Level42 could do better on this, perhaps you don't think so, but I do.

**Comment by gatorheel** [comment]
Code42/Crashplan do not immediately disable old clients.  My install is 6.9.4.502 and is actively backing up new files.  If your client is not backing up, you have something else going on.

**Comment by steveschow** [comment]
Ok.  what else might be going on?  Last time the update wouldn't go through the same thing happened, I started getting messages that my backups are 3 days, 5 days old, etc.. until we updated it and then they went through.  When I manually try to run the backup...it runs for 30 seconds, tells there is there 9GB to backup...but its not getting backed.  I didn't look at the logs because I'm busy today and I pretty much already know the answer is because there is message at the top complaining that it couldn't auto update the software.

**Comment by steveschow** [comment]
Are you sure yours is backup your files?  That is strange its working for you but not for me...  I'd like to know if there is a trick to getting mine to backup while we wait..

**Comment by toledobastos** [comment]
Guys,

I think we should leave this thread for questions related to the update, but my two cent:

> My install is 6.9.4.502 and is actively backing up

Code42 (Level42?) releases updates in batches, so not everyone gets them at the same time. 

> Their clients update automatically

That's accurate, but this time around it seems ver 7.0.0 required a system restart on Windows machines, so the auto-update doesn't always work as intended.

> a setup you created that they never supported in the first place

Back in the day CrashPlan did offer support for headless clients, but that's long gone.

> Unsupported is unsupported

That's right. That's where we are.

**Comment by zombiehoffa** [comment]
My crashplan appears to have updated itself automagically after trying many times over the last 3-4 days.. version 7.0.0.581.  Pleasant surprise.

**Comment by jlesage** [comment]
Yes, a new Docker container image is now available :)

**Comment by Tek4** [comment]
Thank you! 👍
