### ISSUE TITLE
Large filesets, unresponsive Synology

### ISSUE THREAD

**Issue by acseven** [jlesage/docker-crashplan-pro#199]
Hi,
Using a Synology NAS with 4Gb of RAM (3Gb allocated to Crashplan) and around 3.5 Tb in total of data, the NAS is unresponsive after sometime. No backend or other services are accessible, including remote desktop to the Crashplan container or even SSHing the NAS. 

I understand that this is a memory limitation issue which I can only solve with a NAS that supports more memory (mine doesn't and I'm not planning on upgrading right now), but it seems strange that the NAS can't prioritise anything else above Crashplan's container. 

I have the file sets scheduled to work between a strict period of time (night time) and by the morning - when it's supposed to have stopped and I can use the NAS - I find the box completely unresponsive due to heavy HD memory swapping, and there is no alternative to either a) hard shutdown or b) press-power-to-shutdown request that will take at the very least 3 hours to actually turn off the box.

On Synology boxes, CPU limitation doesn't do anything. I also found the APP_NICENESS variable and tried setting it to a high number (15), but it didn't make much difference (if not worse). 

Any thoughts on how to give the system higher priority?

**Comment by jlesage** [comment]
CPU limitation won't help if the device is unresponsive because of heavy memory swapping.  The system unresponsiveness is due to all the I/O operations.

> Any thoughts on how to give the system higher priority?

The memory swapping is not performed by CrashPlan directly, but by the system itself...

CrashPlan requires a lot of memory.  The need increases with the size of the backup.  Did you check advices provided by CrashPlan:

https://support.code42.com/CrashPlan/6/Troubleshooting/Adjust_Code42_app_settings_for_memory_usage_with_large_backups#Alternative_solution

**Comment by acseven** [comment]
> Did you check advices provided by CrashPlan:

I did. I think there's really not much else to be done then.
Thanks
