### ISSUE TITLE
Issue with this container on Synology

### ISSUE THREAD

**Issue by ilkevinli** [jlesage/docker-crashplan-pro#21]
Hi,
     First of all I want to say thanks for your work. I have installed this on my Synology NAS (RS815+) and I am having a strange issue. It sees all of my folders, but it is only backing up the contents of 2 of the folders. I have attached a screenshot of my issue. The command I used to run the docker is this:

docker run -d --name Crashplan -p 5800:5800 -p 5900:5900 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v /volume1:/volume1:rw  jlesage/crashplan-pro

It sees the contents of photos and web, but it can't see the contents of the other folders. Any suggestions ? Thanks

**Comment by jlesage** [comment]
Did you verified that all the folders/subfolders are selected in CrashPlan?
Or maybe a file permission/ownership issue?
On your NAS, check if there is any difference (in user/group) between a folder that works and another that doesn't:
```
ls -l /volume1/music
ls -l /volume1/photo
```

**Comment by ilkevinli** [comment]
Thanks jlesage for your response.

Here is the output from those 2 commands. 
![docker2](https://user-images.githubusercontent.com/10118629/34048503-f4b36b22-e181-11e7-996f-e99f2407fd77.png)

To rule out a permission issue, do you you know the command to get the User and Group ID ? I only have 3 users KC Jenn and Admin. I just run the command to add them all.

Thanks

**Comment by jlesage** [comment]
If your files are owned by multiple users, then you need to make sure to run the container as a user that can access/read all of them.

To rule out a permission issue, you can try to run the container as `root`, by setting the environment variables `USER_ID=0` and `GROUP_ID=0`.

If you want to know the ID of user `KC`:
```
id KC
```

**Comment by bigtfromaz** [comment]
Kevin,

I have a Synology NAS and I think you may be dealing with a permissions issue.  As far as Synology is concerned any folder outside of exposed file shares are theirs.  DSM won’t be shy about setting permissions on volume1 and they’ll change anything they want, anytime they want.  My advice is never do anything on the command line in Synology unless there is no other choice.  If you do, document it and be prepared to redo it, almost certainly after any upgrade activity.

I have had it working on a DS918+ for some time, first on 4.9 and now on 6.

I chose not map the /volume1 folder, because it’s the output of their volume management tool and they’ll alter its permission as they see fit. If you change permissions on /volume1, I am almost certain they will reset them the next time you upgrade DSM.

However, The children of volume1 are file shares and their permissions are under their user management tooling, but they won’t change these folder permission unless you do it using their tooling.  So I mapped the folders like this:

-v /volume1/dir1:/volume1/dir1:rw
-v /volume1/dir2:/volume1/dir2:rw
-v /volume1/dir3:/volume1/dir3:rw
-v /volume1/dir4:/volume1/dir4:rw

All mapped directories were provisioned as file shares using the Synology Shared Folder App in the Control Panel.  I think this is important as that app handles takes care to set security settings that are congruent with DSN’s security profile.

I define the container using their GUI but I suspect that may not matter.  I chose to run the container at “Highest Privilege” but am not sure if that’s root level or not.

In any event it all works perfectly and I can am reasonably certain that other administrative activity will not set privileges that hide files from CrashPlan.

It’s also important to note that the anything outside of the “Shared Folders” on a Synology is fair game.  They are not shy about making changes to configuration when performing upgrades to DSM (their name for their Linux/App build).  As an example any changes you make in the /etc.default folder (this is where their /etc is stored) will be replaced on every DSM upgrade.

**Comment by ilkevinli** [comment]
I just want to thank you both @jlesage  and @bigtfromaz . It was in fact a permission issue. Once I added the USERR_ID and GROUP_ID it worked. Once the backup completes, I'm going to set it up with your method @bigtfromaz 

Here is the command I used for anyone else having this issue:

docker run -d --name Crashplan -p 5800:5800 -p 5900:5900 -e USER_ID=0 -e GROUP_ID=0 -v /volume1/docker/appdata/crashplan-pro:/config:rw -v /volume1:/volume1:rw  jlesage/crashplan-pro

@jlesage I'm going to be sending a donation your way. Do you have a link ? Thanks again

**Comment by jlesage** [comment]
Two notes:
  - While running as root (USER_ID=0, GROUP_ID=0) hide all permission issues, it's not the best choice from a security standpoint.  You want to limit privileges of the container to limit its ability to do nasty things to both your host and itself.
  - `volume1` can be mapped as read-only, unless you need to restore files.  Doing this give you the assurance that the container will not alter your precious data :).

I saw that you found the donation link... thank you very much!

**Comment by ilkevinli** [comment]
@jlesage with that in mind, how is the command used to add multiple user id's ? So instead of me using 
-e USER_ID=0  I need to add user_id's 1024,1026, and 1027. I have tried -e USER_ID=1024:1026:1027 and -e USER_ID=1024,1026,1027 both cause the container to crash on startup. Thanks.

**Comment by jlesage** [comment]
The container can run under a single user.

I saw earlier that most of your files are owned by the group `users`.  So what you could do is create a new `docker` user/group.  Make sure that `docker` is part of group `users`.  Then find the id of `docker` and use it to run the container.

I guess it's this kind of strategy that you could adopt.

**Comment by ilkevinli** [comment]
Am a creating a new USER called docker and adding that to the users group  ? Or am I creating a new GROUP called docker  ? Does either of those need R/W access to all of the folders I am backing up ?

**Comment by jlesage** [comment]
You create a new user called `docker` that you add to group `users` (in linux, when you create a user, a group of the same name is also created, not sure if it's the same thing for Synology).

For backup purpose, no R/W access is needed to `/volume1`.  However, write access is needed for appdata (`/volume1/docker/appdata/crashplan-pro`).

**Comment by excalibr18** [comment]
I noticed that on the Synology when migrating from Patters' CrashPlan app I can more easily take over the existing backup by mapping:
`-v /volume1:/volume1:ro`
instead of
`-v $HOME:/storage:ro`
CrashPlan Pro 6.6.0 automatically recognizes the file section this way and doesn't require re-adding files, and thereby retains file versioning.
