### ISSUE TITLE
Crashplan backup stopped working. Code42 web portal states "Authority Connection Offline". 

### ISSUE THREAD

**Issue by extremegmerusa8** [jlesage/docker-crashplan-pro#273]
Crashplan backup stopped working. Code42 web portal states "Authority Connection Offline".  I am using Crashplan with Synology DS218+. Also, under "Active Devices" in Code42, I see under "Alerts" column, it states "WarningBackupAlert".

**Comment by jlesage** [comment]
What the container app (the container) is showing ?

**Comment by jSFBay** [comment]
Did this get resolved? My data has been sitting for 21 days not getting backed up because of (per support) deep maintenance. But that ended a couple days ago and I also have the "Authority Connection Offline" which I have no idea how to change. Launching the app results in "Trying to Connect" or "Connecting" forever. 

Is "Authority Connection Offline" my problem, and if so, how do I change that? 
Thanks in advance,
Jeff

**Comment by jlesage** [comment]
Can you try to update to the latest Docker image that was released today ?

**Comment by jSFBay** [comment]
Thanks jlesage for the post. The problem seemed to resolve on its own a few days ago and things are now working as expected.

**Comment by jlesage** [comment]
Ok, thanks for the update!

**Comment by JeroenAdam** [comment]
Same issue here on a linux device. Web portal states "Authority Connection Offline.
The client history shows however that there is data tranfer to the destination (when changes have been made)
It occurs from time to time and I tried updating the container to v2.15.0 which did not seem to help.
I always work around the issue by launching a manual maintenance.
This time I tried changing the preference of deep maintenance every 1 day instead of 28 days.
I'll report back in the coming days.

**Comment by cgbale** [comment]
I have the same issue on a Synology server. The container client reports "last backukp 1.8 hours ago". 

The CrashPlan Backup Status Report sends email notifications reporting "Last backup activity: ⚠ 26.8 days ago; Last completed backup: 26.8 days ago"

There is also a message on the main screen of the client saying "Code42 wasn't able to update but will reattempt in 1 hour."

I'm running manual maintenance on the client now and changed Deep Maintenance period from 28 days to 7 days.

**Comment by jlesage** [comment]
@cgbale, update your container image to get the latest CrashPlan version.

**Comment by JeroenAdam** [comment]
The root cause remains, I put my linux device preference 'perform deep maintenance' to every 1 day instead of 28 days.
That assures the "Authority Connection Offline" on the web portal generally has been solved.
But since I'd like to be alerted daily by mail about backup status, I do sometimes recieve the 'not backed up for 1 day' alert in my mailbox.
It's annoying, the backups are done well, but this ailing connection makes it so that the central system does not get that information from the client.
