### ISSUE TITLE
Files from multiple sources.

### ISSUE THREAD

**Issue by metahertz** [jlesage/docker-crashplan-pro#51]
Hi @jlesage 

Awesome work! Question on the Docker build.
Is there a reason for having three different sources of the needed files:

1. Some from your own base image.
2. Some from apt-get in the Dockerfile.
3. Some copied in from the `root` dir in this repo.

I'd like to make a  more 'trusted' build, where each file required (apart from the crashplan binary) comes from the official ubuntu apt repositories. Were there issues you encountered that stopped you doing this in the first place? Any pointers?

Thanks.

**Comment by jlesage** [comment]
In fact, this container is not based on Ubuntu, but on [Alpine Linux](https://alpinelinux.org/).

This means that most packages used in this container image come from the official Alpine Linux repository.  Some other packages are compiled from source, because they are not available on Alpine repository or the version available have missing fixes, features, etc.

As you mentioned, some libraries are manually installed from the `rootfs` directory.  This is needed because Alpine Linux implements libc via [musl](https://www.musl-libc.org/) instead of glibc.  CrashPlan binaries being compiled against glibc, incompatibilities occur when it uses shared library that have been built with musl.  For these incompatibilities, I provide a glibc version of them (they come from Ubuntu).

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
