### ISSUE TITLE
Code 42 is making changes to CrashPlan Pro

### ISSUE THREAD

**Issue by bigtfromaz** [jlesage/docker-crashplan-pro#7]
I received an email from Code42 that they are making a change to the app that removes the ability to run headless.  If I understand your build, you are not actually running headless from their perspective.  Here is the link:
[No more headless](https://support.code42.com/Release_Notes/CrashPlan_for_Small_Business_version_6.6)

Do you plan an attempt to upgrade?  If so, let me know if you need a beta tester.

Cheers

**Comment by jlesage** [comment]
They are probably talking about the "official" headless mode:

https://support.code42.com/CrashPlan/4/Configuring/Use_CrashPlan_on_a_headless_computer

So I agree with you, running in docker container should not be affected.

As soon as the new version is available, I will update the image.  If the new version is already available in your account, you can provide the download link ;)

**Comment by bigtfromaz** [comment]
I don’t see a link yet.  When I do, I’ll send it.

**Comment by FizzGiGG** [comment]
There isn't an "official" headless mode, it was all unsupported. Now it will be completely removed, not that it affects this image, just clarifying.

> Although running the CrashPlan service on a headless computer is an unsupported feature, this article describes a process that some users have found useful.

**Comment by ChuckDavis666** [comment]
This was the text of the e-mail from CrashPlan:

As you’ve heard, the CrashPlan for Small Business desktop client – specifically the newly upgraded Version 6 Code42 app – means that you’ll now have the same core technology that the world’s largest brands rely on for peace of mind to bounce back faster.

It also means some of the ways you’ve been using CrashPlan for Small Business may be impacted – and may no longer work. Please see here for our recommended and supported set up, including alternatives for 32-bit Linux and headless/NAS configurations. 
 
We want to make sure you have the resources to best use CrashPlan for Small Business successfully.

Sincerely,
Your CrashPlan for Small Business Team

*********

This was the meat of the linked page from the e-mail:

November 28, 2017
Version 6.6.0 of the CrashPlan for Small Business app simplifies life for administrators and users with an overhauled user interface, which makes it even easier to manage and use CrashPlan for Small Business for backup and recovery. The release began on November 28, 2017, and the new app will automatically become available to all customers and trial users over the next few months.

See Changes to the Code42 app in version 6 for complete details, including the new and improved replace device wizard and additional resources. 

Version 6.6.0 of the CrashPlan for Small Business app is currently only available for Windows and Linux devices. 
Devices running 32-bit Linux systems remain unsupported. Beginning with version 6.6.0, the CrashPlan for Small Business app does not function on 32-bit Linux devices. Review the CrashPlan for Small Business requirements to ensure your system is compatible with the new and improved app.  
Using CrashPlan for Small Business on a headless computer and installing CrashPlan for Small Business on a NAS device remain unsupported. Beginning with version 6.6.0, the CrashPlan for Small Business app does not function in either of these configurations. See Back up networked storage or NAS devices for additional options.   

********

These were responses today from CrashPlan tech support:

We are upgrading CrashPlan to use the same interface and engine as our enterprise product, hence the large change to the version numbers.

CrashPlan has never supported headless configurations running on NAS hardware, and we will continue to not support these setups. Beginning with version 6.6, existing headless configurations will no longer work. In order to continue using CrashPlan, you will need to switch to a normal CrashPlan installation. More information can be found here:
•	https://support.code42.com/CrashPlan/6/Backup/Back_up_networked_storage_or_NAS_devices

*******

Good luck!

**Comment by taeris** [comment]
New version of CrashPlan SmB
https://web-lbm-msp.crashplanpro.com/client/installers/CrashPlanSmb_6.6.0_1506661200660_4347_Linux.tgz

Cheers

**Comment by jlesage** [comment]
Thanks @taeris !
I'm starting working on this :)

**Comment by ChuckDavis666** [comment]
Don't be nervous, but lots of people are watching over your shoulder.  ;-)

**Comment by bigtfromaz** [comment]
After studying jlesage’s work, and the Docker file, I am not worried 😊

**Comment by jlesage** [comment]
I have now a working version :)

I will do a beta image that will be available on docker hub.  I will use it to test upgrade over previous versions.

**Comment by jlesage** [comment]
I tried the image against by existing installation.  Looks to work fine the first time, but after a container restart, the app fails to login.

**Comment by jlesage** [comment]
Image with CP 6.6.0 now available.  Enjoy!
