### ISSUE TITLE
Running command on container startup

### ISSUE THREAD

**Issue by maluht** [jlesage/docker-crashplan-pro#77]
Is there any way to run a mount command on startup? I would like to mount a set of network shares so the data can be backed up. I tried extending the container and running the mount command as a ENTRYPOINT, but this fails. Any advice would be greatly appreciated.

Best regards
Mads

**Comment by bigtfromaz** [comment]
I think you would have to mount them on the host and then map the volumes accordingly when you define/start the container.  You could do that in a script when you start the container.

I don’t know if Crashplan will behave differently when it sees a mount point and not a file system folder.

If you do this and the file systems are unmounted while the container is running, Crashplan will most likely treat the files as deleted.  I don’t think this is a good idea because a network failure or a server shutdown could cause Crashplan to delete your files in the archive.

**Comment by jlesage** [comment]
I agree, volume mappings is the way to go.
I don't think mounting from the container is a good idea.  You will need to give more privileges to the container or run it in privileged mode.

**Comment by maluht** [comment]
@bigtfromaz thanks for your suggestion, but this is not possible in windows. Crashplan do not delete files that are removed from your disk, so thats not a problem at all. I just need a way to run a command on startup, so I can mount my network shares. Must be possible somehow :)

**Comment by bigtfromaz** [comment]
Okay.  This is a Linux container so I gather that you are running Docker for Windows in Linux mode.  Is that correct?  I am also getting that you are doing this because CrashPlan for Windows will not back up a file share.  In any event, I would probably not use Docker for Windows in Linux mode.  It creates an Linux VM for it's own use.   I would rather create a Linux VM for my own use, mount the file share in the VM using SMB, installer Docker and run this image there; much cleaner.

If you are using Docker for Windows, I am not sure you need, or want, to map a file share to a drive letter.  I suspect that instead of D:\... you you could use a URI like \\yourHostName.yourDomainName\yourShareName\... when mapping the volume in your docker run command.  This would be easier if you are using a Active Directory (Azure Directory) for single sign on.  If not you'll have to find a way to provide credentials.

You can create a PowerShell script or .bat file that mounts the file shares and then issues the docker run command.  If you are able to use the URI approach you won't to map the drives. 

Scripts can be run on demand or you can create a task in the Task Scheduler and have it run the script a few minutes after startup.  If you don't want it to run all the time, you can write another script that stops the container and run it on a schedule as well.

Also there is a backup setting that tells CrashPlan whether or not to remove deleted files from the archive when they disappear from the source.  Make sure it set the right way.

Good places to get Windows advice on automatically mapping file shares and managing credentials would include forums at Microsoft or Stack Exchange  

If I misunderstood, please me more specific and verbose regarding your environment and requirements.

**Comment by pabloa** [comment]
Having windows is a bad idea :)

But if you cannot get rid of it, you could create a Ubuntu Virtual machine using VirtualBox or similar. Inside that VM you install docker and docker-crashplan-pro. 

You configure the Ubuntu VM to mount whatever you need at start up.

After that you could make it work with some cron to start the VM in some moment of the day (or night) so the backup program can run.

I did that in my company's cluster (using linux, but it is applicable if you virtualize the host running docker) and it works.
