### ISSUE TITLE
Multiple partitions question

### ISSUE THREAD

**Issue by tlc** [jlesage/docker-crashplan-pro#78]
I'm moving from CrashPlan home.  My current backup includes 

> /home/A
> /home/B
> /data/C
> /data/D

Should I mount /home and /data under storage?

> -v /home:/storage/home:ro -v /data:/storage/data:ro

Or mount them so the original paths can be used.

> -v /data:/data:ro -v /home/A:/home/A:ro  ...

Thanks!

**Comment by jlesage** [comment]
It's up to you.  It depends on how you would like to manage your files in CrashPlan.

The advantage of keeping all data to backup under `/storage` is that it's easier to manager files to backup since everything is under the same directory.

The advantage of keeping the original paths is that the transition would be easier in the sense that you won't have to re-select your files in CrashPlan.

**Comment by tlc** [comment]
I can handle re-selecting, but will the change in paths cause everything to be re-uploaded?  Or is CP smarter than that?

**Comment by jlesage** [comment]
Because of deduplication, nothing will be re-uploaded.

In case you didn't see it, there is some documentation about this process:
https://github.com/jlesage/docker-crashplan-pro#taking-over-existing-backup
